name: Publication

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '8'
          cache: gradle

      - name: Checkout maven branch
        uses: actions/checkout@v4
        with:
          ref: maven
          path: build/maven

      - name: Build with Gradle
        env:
          IS_PUBLICATION: true
        run: |
          rm -rf ./build/maven/.git
          chmod +x ./gradlew
          ./gradlew publish -iS

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs

      - name: Create release and upload binaries
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: build/libs/*

      - name: Deploy to Maven branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: maven
          folder: build/maven